apiVersion: v1
kind: Service
metadata:
  name: sctp-service
  labels:
    app: sctpserver
spec:
  clusterIP: None
  ports:
    - protocol: SCTP
      port: 11111
      name: sctpserver
  selector:
    app: sctpserver
